apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
      - name: service-2
        image: 182399685065.dkr.ecr.us-east-1.amazonaws.com/ecr1:s2
        ports:
        - containerPort: 8001
        env:
        - name: SECRET_KEY
          value: "007secret"