apiVersion: v1
kind: Service
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: service-2