apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
      - name: service-b
        image: <your-dockerhub-username>/service-2:latest
        ports:
        - containerPort: 8001
        env:
        - name: SECRET_KEY
          value: "007secret"