apiVersion: v1
kind: Service
metadata:
  name: service-1
  labels:
    app: service-1
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: service-1