apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  labels:
    app: service-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: 182399685065.dkr.ecr.us-east-1.amazonaws.com/ecr1:s1
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "007secret"
        - name: SERVICE_2_URL
          value: "http://service-2.default.svc.cluster.local:8001/validate-token"