apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  labels:
    app: service-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: <your-dockerhub-username>/service-1:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "007secret"
        - name: SERVICE_2_URL
          value: "http://service-2.default.svc.cluster.local/validate-token"